### ISSUE TITLE
Мероприятия — обновление мероприятия

### ISSUE THREAD

**Issue by matveycodes** [ClassroomBookingTeam/repository#13]
# Описание

Необходимо разработать эндпоинт, позволяющий обновить мероприятие.

Все поля тела запроса опциональны (обновляем только переданные).

## Метод

PATCH /v1/events/{eventId}/

## Права доступа

Доступен только для авторизованных пользователей с ролью `teacher`. Редактирование доступно только для создателя мероприятия.

## Тело запроса

```json
{
  "title": "Консультация по моделированию",
  "description": "Суперкрутая консультация",
  "date_from": "2024-02-05T11:58:26+07:00",
  "date_to": "2024-02-05T11:58:26+07:00",
  "recurrence": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "recurrence_until": "2024-04-04T19:48:28.917Z",
  "max_appointments": 0
}
```

### 200

Мероприятие успешно обновлено.

```json
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "user": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "email": "user@example.com",
    "roles": [
      "teacher"
    ],
    "first_name": "Иван",
    "last_name": "Иванов",
    "middle_name": "Иванович",
    "short_name": "Иванов И. И.",
    "full_name": "Иванов Иван Иванович"
  },
  "room": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "number": "501л",
    "floor": 5,
    "building": {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "УЛК"
    }
  },
  "title": "Консультация по моделированию",
  "description": "Суперкрутая консультация",
  "recurrence": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "name": "Каждый день"
  },
  "recurrence_until": "2024-02-05T11:58:26+07:00",
  "date_from": "2024-02-05T11:58:26+07:00",
  "date_to": "2024-02-05T11:58:26+07:00",
  "appointment_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "appointments_count": 0,
  "max_appointments": 0,
  "remaining_appointments": 0
}
```

### 400

Формат запроса некорректен или не выполнены условия для его успешного завершения.

```json
[
  {
    "message": "Ошибка",
    "path": "title" | "room" | "description" | "date_from" | "date_to" | "recurrence" | "recurrence_until" | "max_appointments"
  }
]
```

### 403

Пользователь не авторизован и/или отсутствует сессионная cookie, пользователь не является преподавателем, мероприятие не принадлежит пользователю.

```json
[
  {
    "message": "string",
    "path": null
  }
]
```

### 404

Мероприятие не найдено.

```json
[
  {
    "message": "string",
    "path": null
  }
]
```

# Тестирование

Следует проверить поведение Системы при:
* отправке запроса неавторизованным пользователем (ответ 403)
* отправке запроса авторизованным пользователем с ролью `student` и некорректным телом (ответ 403)
* отправке запроса авторизованным пользователем с ролью `student` и корректным телом (ответ 403)
* отправке запроса авторизованным пользователем с ролью `student` и некорректным ID (ответ 403)
* отправке запроса авторизованным пользователем с ролью `teacher` и некорректным телом (ответ 400)
* отправке запроса авторизованным пользователем с ролью `teacher` и корректным телом (ответ 200)
* отправке запроса авторизованным пользователем с ролью `student` и некорректным ID (ответ 404)

**Comment by SpectralOne** [comment]
решено в #35
