### ISSUE TITLE
Повторения — получить повторения

### ISSUE THREAD

**Issue by matveycodes** [ClassroomBookingTeam/repository#17]
# Описание

Необходимо разработать эндпоинт, позволяющий получить список повторений.

## Метод

GET /v1/recurrences/

## Права доступа

Доступен только для авторизованных пользователей.

## Тело запроса

<Отсутствует>

### 200

Повторения успешно получены.

```json
[
  {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "name": "Каждый день"
  }
]
```

### 403

Пользователь не авторизован и/или отсутствует сессионная cookie.

```json
[
  {
    "message": "string",
    "path": null
  }
]
```

# Тестирование

Следует проверить поведение Системы при:
* отправке запроса неавторизованным пользователем (ответ 403)
* отправке запроса авторизованным пользователем при отсутствии повторений в Системе (ответ 200)
* отправке запроса авторизованным пользователем при наличии повторений в Системе (ответ 200)

**Comment by SpectralOne** [comment]
решено в #37
