### ISSUE TITLE
Авторизация — логаут

### ISSUE THREAD

**Issue by matveycodes** [ClassroomBookingTeam/repository#2]
# Описание

Необходимо разработать эндпоинт, позволяющий пользователям выходить из своего аккаунта в Системе (см. [пункт ТЗ](https://github.com/ClassroomBookingTeam/repository/wiki/Техническое-задание#23-авторизация)).

Пользователя идентифицирует по cookie, которая была установлена при авторизации. При успешном выходе cookie cбрасывается.

После выхода из Системы токен пользователя отмечается как неактивный (по нему больше нельзя получить доступ к другим эндпоинтам).

## Метод

DELETE /v1/session/

## Права доступа

Доступен только для авторизованных пользователей.

## Тело запроса

<Отсутствует>

### 200

Сессия успешно удалена — сбрасываем cookie.

<Тело ответа отсутствует>

### 403

Пользователь не авторизован и/или отсутствует сессионная cookie.

```json
[
  {
    "message": "string",
    "path": null
  }
]
```

# Тестирование

Следует проверить поведение Системы при:
* отправке запроса неавторизованным пользователем (ответ 403)
* отправке запроса авторизованным пользователем (ответ 200)

**Comment by archeoss** [comment]
Решено в #39
