### ISSUE TITLE
Пользователь — получение текущего юзера

### ISSUE THREAD

**Issue by matveycodes** [ClassroomBookingTeam/repository#3]
# Описание

Необходимо разработать эндпоинт, позволяющий получить информацию о текущем пользователе — том, кому принадлежит сессионный токен, переданный в cookie запроса.

## Метод

GET /v1/users/current/

## Права доступа

Доступен только для авторизованных пользователей.

## Тело запроса

<Отсутствует>

### 200

Информация о пользователе успешно получена.

```json
{
  "id": "string",
  "email": "string",
  "roles": [
    "string"
  ],
  "first_name": "string",
  "last_name": "string",
  "middle_name": "string",
  "short_name": "string",
  "full_name": "string"
}
```

### 403

Пользователь не авторизован и/или отсутствует сессионная cookie.

```json
[
  {
    "message": "string",
    "path": null
  }
]
```

# Тестирование

Следует проверить поведение Системы при:
* отправке запроса неавторизованным пользователем (ответ 403)
* отправке запроса авторизованным пользователем (ответ 200)

**Comment by SpectralOne** [comment]
решено в #30
