### ISSUE TITLE
Корпусы — получение аудиторий корпуса

### ISSUE THREAD

**Issue by matveycodes** [ClassroomBookingTeam/repository#7]
# Описание

Необходимо разработать эндпоинт, позволяющий получить список аудиторий конкретного корпуса.

Сортировка по умолчанию по двум ключам: по возрастанию номера этажа и возрастанию номера аудитории (чтобы в массиве сначала были все аудитории первого этажа, отсортированные по возрастанию номеров, потом — аудитории второго этажа и так далее).

## Метод

GET /v1/buildings/{buildingId}/rooms/

## Права доступа

Доступен только для авторизованных пользователей.

### Параметры

* `page_size` — максимальное количество элементов на одной странице (по умолчанию 20)
* `page` — номер запрашиваемой страницы, нумерация с 1 (по умолчанию 1)
* `available_at` — ISO8601-дата, в которую аудитория свободна

### 200

Аудитории успешно получены.

```json
{
  "count": 100,
  "next": 2,
  "previous": null,
  "results": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "number": "501л",
      "floor": 5,
      "building": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "name": "УЛК"
      }
    }
  ]
}
```

### 403

Пользователь не авторизован и/или отсутствует сессионная cookie.

```json
[
  {
    "message": "string",
    "path": null
  }
]
```

### 404

Корпус не найден.

```json
[
  {
    "message": "string",
    "path": null
  }
]
```

# Тестирование

Следует проверить поведение Системы при:
* отправке запроса неавторизованным пользователем (ответ 403)
* отправке запроса авторизованным пользователем при отсутствии корпуса в Системе (ответ 404)
* отправке запроса авторизованным пользователем при отсутствии аудиторий в Системе (ответ 200)
* отправке запроса авторизованным пользователем при наличии аудиторий в Системе (ответ 200)

**Comment by SpectralOne** [comment]
решено в #32
