### ISSUE TITLE
Аудитории — получение аудитории

### ISSUE THREAD

**Issue by matveycodes** [ClassroomBookingTeam/repository#9]
# Описание

Необходимо разработать эндпоинт, позволяющий получить аудиторию.

## Метод

GET /v1/rooms/{roomId}/

## Права доступа

Доступен только для авторизованных пользователей.

## Тело запроса

<Отсутствует>

### 200

Аудитория успешно получена.

```json
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "number": "501л",
  "floor": 5,
  "building": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "name": "УЛК"
  }
}
```

### 403

Пользователь не авторизован и/или отсутствует сессионная cookie.

```json
[
  {
    "message": "string",
    "path": null
  }
]
```

### 404

Аудитория не найдена.

```json
[
  {
    "message": "string",
    "path": null
  }
]
```

# Тестирование

Следует проверить поведение Системы при:
* отправке запроса неавторизованным пользователем (ответ 403)
* отправке запроса авторизованным пользователем при отсутствии аудитории в Системе (ответ 404)
* отправке запроса авторизованным пользователем при наличии аудитории в Системе (ответ 200)

**Comment by SpectralOne** [comment]
решено в #33
